version: "3.9"
services:
  web:
    container_name: go-manager
    build:
      context: .
      dockerfile: docker/go/Dockerfile
      target: $target
      args:
        GO_VERSION: 19.2
    image: go-manager:19.2-${target}
    ports:
      - "9090:9090"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - .:/app
    tty: true
  envoy:
    build:
      context: .
      dockerfile: docker/envoy/Dockerfile
    image: grpcweb/envoy
    ports:
      - "8080:8080"
      - "9901:9901"
  mysql:
    image: mysql:8.0
    ports:
      - "127.0.0.1:3306:3306"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --general-log=1 --general-log-file=/tmp/mysql.log
    user: "1000:1000"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
      - pfm-db-data:/var/lib/mysql
networks:
  default:
    name: pfm-network
    external: true

volumes:
  pfm-db-data:
