name: Go Manager CD

on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.19
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -covermode=atomic -coverprofile=cover.out ./... -v -coverpkg=./... &&
          go tool cover -html=cover.out -o cover.html &&
          go test -json -coverprofile=cover.json ./...
      - uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: cover.*
  quality:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: test-reports
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
