name: Go Manager CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  buildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -covermode=atomic -coverprofile=coverage.out ./... > cover.out
    - name: Results
      run: go test -json -coverprofile=cover.out ./... > result.json

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
    
